package com.pms.model;

public class Employee {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.FIRST_NAME
     *
     * @mbg.generated Wed Jun 13 16:05:00 CST 2018
     */
    private String firstName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.LAST_NAME
     *
     * @mbg.generated Wed Jun 13 16:05:00 CST 2018
     */
    private String lastName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.AGE
     *
     * @mbg.generated Wed Jun 13 16:05:00 CST 2018
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.SEX
     *
     * @mbg.generated Wed Jun 13 16:05:00 CST 2018
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.INCOME
     *
     * @mbg.generated Wed Jun 13 16:05:00 CST 2018
     */
    private Float income;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.FIRST_NAME
     *
     * @return the value of employee.FIRST_NAME
     *
     * @mbg.generated Wed Jun 13 16:05:00 CST 2018
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.FIRST_NAME
     *
     * @param firstName the value for employee.FIRST_NAME
     *
     * @mbg.generated Wed Jun 13 16:05:00 CST 2018
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName == null ? null : firstName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.LAST_NAME
     *
     * @return the value of employee.LAST_NAME
     *
     * @mbg.generated Wed Jun 13 16:05:00 CST 2018
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.LAST_NAME
     *
     * @param lastName the value for employee.LAST_NAME
     *
     * @mbg.generated Wed Jun 13 16:05:00 CST 2018
     */
    public void setLastName(String lastName) {
        this.lastName = lastName == null ? null : lastName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.AGE
     *
     * @return the value of employee.AGE
     *
     * @mbg.generated Wed Jun 13 16:05:00 CST 2018
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.AGE
     *
     * @param age the value for employee.AGE
     *
     * @mbg.generated Wed Jun 13 16:05:00 CST 2018
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.SEX
     *
     * @return the value of employee.SEX
     *
     * @mbg.generated Wed Jun 13 16:05:00 CST 2018
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.SEX
     *
     * @param sex the value for employee.SEX
     *
     * @mbg.generated Wed Jun 13 16:05:00 CST 2018
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.INCOME
     *
     * @return the value of employee.INCOME
     *
     * @mbg.generated Wed Jun 13 16:05:00 CST 2018
     */
    public Float getIncome() {
        return income;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.INCOME
     *
     * @param income the value for employee.INCOME
     *
     * @mbg.generated Wed Jun 13 16:05:00 CST 2018
     */
    public void setIncome(Float income) {
        this.income = income;
    }
}